export {
  FAQ_ASSISTANT_NAME,
  FAQ_OUT_OF_SCOPE_MESSAGE,
  FAQ_SECURITY_GUARD_MESSAGE,
  PLATFORM_INFO_CONTEXT,
  FAQ_SYSTEM_PROMPT,
  FAQ_RESPONSE_FORMAT_RULES,
} from '../tutorsphere-assistant/promptRules.js';

export {
  ASK_LEARN_ASSISTANT_NAME,
  ASK_LEARN_OUT_OF_SCOPE_MESSAGE,
  ASK_LEARN_SYSTEM_PROMPT,
} from '../ask-and-learn-ai/promptRules.js';

export {
  ROADMAP_FINDER_ASSISTANT_NAME,
  ROADMAP_OUT_OF_SCOPE_MESSAGE,
  ROADMAP_SYSTEM_PROMPT,
} from '../roadmap-finder/promptRules.js';
